language: java
jdk:
  - openjdk8

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2'

script: "./mvnw clean install -DskipTests"

notifications:
  email:
    recipients:
      - do-ockhyun@naver.com