
spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  session:
    store-type: jdbc
server:
  servlet:
    session:
      timeout: 7d